# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainmodels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('commentDesc', models.CharField(max_length=250)),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('courseShortDesc', models.CharField(max_length=50)),
                ('courseFullDesc', models.TextField()),
                ('courseThumbnail', models.ImageField(upload_to=mainmodels.models.Course.get_upload_path_thumbnail)),
                ('previewVideoFile', models.FileField(upload_to=mainmodels.models.Course.get_upload_path_preview)),
                ('coursePrice', models.FloatField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField()),
                ('isPublish', models.BooleanField()),
                ('discountPercentage', models.IntegerField()),
                ('discountPrice', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmodels.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedCourse',
            fields=[
                ('featuredCourseID', models.AutoField(primary_key=True, serialize=False)),
                ('expireDate', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmodels.Course')),
            ],
        ),
        migrations.CreateModel(
            name='OrderVideoInCourse',
            fields=[
                ('orderVideoInCourseID', models.AutoField(primary_key=True, serialize=False)),
                ('orderNo', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmodels.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default='Your bio', max_length=255)),
                ('profilePicture', models.ImageField(upload_to=mainmodels.models.Profile.get_upload_path_profilepicture)),
                ('address', models.CharField(default='Your address', max_length=255)),
                ('birthDate', models.DateField(auto_now_add=True)),
                ('balance', models.FloatField(default=0.0)),
                ('gender', models.CharField(max_length=1)),
                ('isBan', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('reviewDesc', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('reviewedDate', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmodels.Course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('courseID', models.IntegerField()),
                ('coursePrice', models.FloatField()),
                ('takerID', models.IntegerField()),
                ('takerBalanceBeforePurchased', models.FloatField()),
                ('usedCoupon', models.BooleanField()),
                ('transactionDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoID', models.AutoField(primary_key=True, serialize=False)),
                ('videoName', models.CharField(max_length=50)),
                ('videoFile', models.FileField(upload_to=mainmodels.models.Video.get_upload_path)),
                ('videoDesc', models.CharField(max_length=250)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmodels.Course')),
            ],
        ),
        migrations.AddField(
            model_name='ordervideoincourse',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmodels.Video'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmodels.Video'),
        ),
    ]
