# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('serial', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('transaction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainmodels.Transaction')),
            ],
        ),
    ]
