# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePreview',
            fields=[
                ('coursePreviewID', models.AutoField(primary_key=True, serialize=False)),
                ('previewVideo', models.FileField(upload_to='previews/')),
                ('isDelete', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmodels.Course')),
            ],
        ),
    ]
