# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import mainmodels.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseFullDesc',
            field=models.TextField(default='Course full description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(default='Course name', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseShortDesc',
            field=models.CharField(default='Course short description', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseThumbnail',
            field=models.ImageField(default='thumbnails/dummies/untitled.png', upload_to=mainmodels.models.get_upload_path_thumbnail),
        ),
        migrations.AlterField(
            model_name='course',
            name='previewVideoFile',
            field=models.FileField(default='previews/dummies/blankvideo.mp4', upload_to=mainmodels.models.get_upload_path_preview),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(default='thumbnails/dummies/untitled.png', upload_to=mainmodels.models.get_upload_path_profilepicture),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoFile',
            field=models.FileField(default='previews/dummies/blankvideo.mp4', upload_to=mainmodels.models.get_upload_path_video),
        ),
    ]
