# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainmodels', '0002_coursepreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], max_length=1)),
                ('profilePicture', models.ImageField(upload_to='profilepics/')),
                ('address', models.CharField(max_length=300)),
                ('birthDate', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('isBan', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
