# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0002_auto_20161031_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentDesc',
            field=models.CharField(default='your comment', max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursePrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='course',
            name='discountPercentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='discountPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='course',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='isPublish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordervideoincourse',
            name='orderNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewDesc',
            field=models.CharField(default='review description', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='courseID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coursePrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='takerBalanceBeforePurchased',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='takerID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='usedCoupon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoDesc',
            field=models.CharField(default='video description', max_length=250),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoName',
            field=models.CharField(default='video name', max_length=50),
        ),
    ]
