# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
