# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 05:24
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0004_auto_20161026_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='isBan',
            field=models.BooleanField(default=False),
        ),
    ]
