# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0005_auto_20161026_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
    ]
