# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainmodels', '0007_auto_20161027_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('reviewDesc', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
                ('reviewDate', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmodels.Course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
