# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0008_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderVideoInCourse',
            fields=[
                ('orderVideoInCourseID', models.AutoField(primary_key=True, serialize=False)),
                ('orderNo', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmodels.Course')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmodels.Video')),
            ],
        ),
    ]
